Vihanga MD V3...

[©] New Features

 > Fix button [ original whatsapp not showd button messages]
 > add .nopeople command.
 > add .ehi command
 > add .ssh command
 > add .logo command
 > add advanced yt down cmd. [.ytdl]
 > and more...
